version: "3"
services:
  backend:
    build: ./backend/
    restart: on-failure
    env_file:
      - ./.env
      - ./.env.secret
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres:10.3-alpine"
    restart: always
    env_file:
      - ./.env.secret
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env.secret
  frontend:
    environment:
      - HOST=0.0.0.0
    build: ./frontend/
    command: npm run dev
    volumes:
      - ./frontend:/www/frontend
      - /www/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  postgres:
    external: true
  node-modules:
