version: "3"
services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env
      - ./.env.secret
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres:10.3-alpine"
    restart: always
    env_file:
      - ./.env.secret
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env.secret
volumes:
  postgres:
    external: true
